Run ('MasterSCADA4D.exe', '',@SW_SHOW)
WinWaitActive ("[CLASS:#32770]", "&Да", 300)
ControlClick("[CLASS:#32770]", "&Да", '[CLASS:Button; INSTANCE:1]')
WinWaitActive ("Установка MasterSCADA 4D Beta", "Вперед", 300)
ControlClick("Установка MasterSCADA 4D Beta", "Вперед", '[CLASS:WindowsForms10.BUTTON.app.0.390be75_r35_ad2; INSTANCE:1]')
WinWaitActive ("Установка MasterSCADA 4D Beta", "Я принимаю условия лицензионного соглашения", 300)
ControlClick("Установка MasterSCADA 4D Beta", "Я принимаю условия лицензионного соглашения", '[CLASS:WindowsForms10.BUTTON.app.0.390be75_r35_ad2; INSTANCE:1]')
Sleep(100)
ControlClick("Установка MasterSCADA 4D Beta", "Я принимаю условия лицензионного соглашения", '[CLASS:WindowsForms10.BUTTON.app.0.390be75_r35_ad2; INSTANCE:3]')
WinWaitActive ("Установка MasterSCADA 4D Beta", "Вперед", 300)
ControlClick("Установка MasterSCADA 4D Beta", "Вперед", '[CLASS:WindowsForms10.BUTTON.app.0.390be75_r35_ad2; INSTANCE:4]')
WinWaitActive ("Установка MasterSCADA 4D Beta", "Завершить", 300)
ControlClick("Установка MasterSCADA 4D Beta", "Завершить", '[CLASS:WindowsForms10.BUTTON.app.0.390be75_r35_ad2; INSTANCE:2]')

